image: laurentdoguin/workspace-couchbase-java-17

# Commands that will run on workspace start
tasks:
  - name: Start Couchbase Server
    command: |
      sudo /entrypoint.sh couchbase-server
  - name: Build the Java Project
    init: |
      source ./scripts/setLocalEnv
      eval $(gp env -e)
    command: |
      gp await-port 8091
      cbsh -c "source ./scripts/dbSetup.nu; dbSetup $COUCHBASE_DEFAULT_BUCKET $COUCHBASE_DEFAULT_SCOPE $COUCHBASE_DEFAULT_COLLECTION"
      ./gradlew build

# PreInstalled Couchbase and Java Extension
vscode:
    extensions:
        - "couchbase.vscode-couchbase"
        - "redhat.java"
        - "vscjava.vscode-java-dependency"
        - "vscjava.vscode-java-debug"
        - "github.vscode-github-actions"

# exposed ports
ports:
- port: 8080 # Application
  onOpen: open-browser
- port: 8091 # Couchbase Web console, REST/HTTP interface
  onOpen: open-browser
  visibility: public
- port: 8092 # Views, queries, XDCR
  onOpen: ignore
- port: 8093 # Query services (4.0+)
  onOpen: ignore
- port: 8094 # Full-text Search (4.5+)
  onOpen: ignore
- port: 8095 # Analytics (5.5+)
  onOpen: ignore
- port: 8096 # Eventing (5.5+)
  onOpen: ignore
- port: 11207 # Smart client library data node access (SSL)
  onOpen: ignore
- port: 11210 # Smart client library/moxi data node access
  onOpen: ignore
- port: 11211 # Legacy non-smart client library data node access
  onOpen: ignore
- port: 18091 # Couchbase Web console, REST/HTTP interface (SSL)
  onOpen: ignore
- port: 18092 # Views, query, XDCR (SSL)
  onOpen: ignore
- port: 18093 # Query services (SSL) (4.0+)
  onOpen: ignore
- port: 18094 # Full-text Search (SSL) (4.5+)
  onOpen: ignore
- port: 18095 # Analytics (SSL) (5.5+)
  onOpen: ignore
- port: 18096 # Eventing (SSL) (5.5+)
  onOpen: ignore
- port: 9100
  onOpen: ignore
- port: 9101
  onOpen: ignore
- port: 9102
  onOpen: ignore
- port: 9103
  onOpen: ignore
- port: 9105
  onOpen: ignore
- port: 9123
  onOpen: ignore
- port: 9130
  onOpen: ignore
- port: 9998
  onOpen: ignore
- port: 9999
  onOpen: ignore
- port: 11206
  onOpen: ignore
- port: 11209
  onOpen: ignore
- port: 11280
  onOpen: ignore
- port: 19102
  onOpen: ignore
- port: 19130
  onOpen: ignore
- port: 21100
  onOpen: ignore
- port: 21200
  onOpen: ignore
- port: 21300
  onOpen: ignore
- port: 33059
  onOpen: ignore
- port: 35253
  onOpen: ignore
- port: 36031
  onOpen: ignore
- port: 44889
  onOpen: ignore
